### ISSUE TITLE
can't run the app with docker-compose - no main class detected

### ISSUE THREAD

**Issue by belfz** [elleFlorio/scalachain#21]
Hey,

First of all - thank for an awesome article!

I noticed that I can't run the project with `docker-compose up` (after a successful build). This is what I get:

```
~/projects/scalachain(master*) » docker-compose up
Starting scalachain_node2_1 ... done
Starting scalachain_node1_1 ... done
Starting scalachain_seed_1  ... done
Attaching to scalachain_seed_1, scalachain_node1_1, scalachain_node2_1
seed_1   | Running local source code
seed_1   | copying local sources from /tmp/scalachain to /development
node1_1  | Running local source code
node2_1  | Running local source code
node2_1  | copying local sources from /tmp/scalachain to /development
node1_1  | copying local sources from /tmp/scalachain to /development
node2_1  | [warn] No sbt.version set in project/build.properties, base directory: /development
node1_1  | [warn] No sbt.version set in project/build.properties, base directory: /development
seed_1   | [warn] No sbt.version set in project/build.properties, base directory: /development
node2_1  | [info] Set current project to development (in build file:/development/)
node1_1  | [info] Set current project to development (in build file:/development/)
seed_1   | [info] Set current project to development (in build file:/development/)
node2_1  | [error] java.lang.RuntimeException: No main class detected.
node2_1  | [error]      at scala.sys.package$.error(package.scala:26)
node2_1  | [error] (Compile / bgRun) No main class detected.
node2_1  | [error] Total time: 8 s, completed Apr 14, 2019 6:48:34 PM
node1_1  | [error] java.lang.RuntimeException: No main class detected.
node1_1  | [error]      at scala.sys.package$.error(package.scala:26)
node1_1  | [error] (Compile / bgRun) No main class detected.
node1_1  | [error] Total time: 8 s, completed Apr 14, 2019 6:48:34 PM
scalachain_node2_1 exited with code 1
scalachain_node1_1 exited with code 1
seed_1   | [error] java.lang.RuntimeException: No main class detected.
seed_1   | [error]      at scala.sys.package$.error(package.scala:26)
seed_1   | [error] (Compile / bgRun) No main class detected.
seed_1   | [error] Total time: 8 s, completed Apr 14, 2019 6:48:36 PM
scalachain_seed_1 exited with code 1
```

**Comment by elleFlorio** [comment]
Hi!

Thank you, and sorry for the super late response! I totally missed this issue... 😅  
Anyway, I'll look into it ASAP! 😉

**Comment by elleFlorio** [comment]
Hi,

I tried to start everything from scratch following the instructions, and everything seems ok. I run the code in branch master. However, my logs are a little different:
```
Development/scala/scalachain  master ✔                                                                                       44d
▶ docker-compose up
Starting scalachain_node1_1 ... done
Starting scalachain_node2_1 ... done
Starting scalachain_seed_1  ... done
Attaching to scalachain_node1_1, scalachain_node2_1, scalachain_seed_1
node1_1  | Running local source code
node1_1  | copying local sources from /tmp/scalachain to /development
node2_1  | Running local source code
node2_1  | copying local sources from /tmp/scalachain to /development
seed_1   | Running local source code
seed_1   | copying local sources from /tmp/scalachain to /development
node1_1  | [info] Loading project definition from /development/project
seed_1   | [info] Loading project definition from /development/project
node2_1  | [info] Loading project definition from /development/project
seed_1   | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node1_1  | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node2_1  | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node1_1  | [info] Done updating.
node2_1  | [info] Done updating.
seed_1   | [info] Done updating.
seed_1   | [info] Loading settings for project development from build.sbt ...
seed_1   | [info] Set current project to scalachain (in build file:/development/)
node2_1  | [info] Loading settings for project development from build.sbt ...
node1_1  | [info] Loading settings for project development from build.sbt ...
node2_1  | [info] Set current project to scalachain (in build file:/development/)
node1_1  | [info] Set current project to scalachain (in build file:/development/)
seed_1   | [info] Updating ...
node2_1  | [info] Updating ...
node1_1  | [info] Updating ...
seed_1   | [info] Done updating.
seed_1   | [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
node2_1  | [info] Done updating.
node2_1  | [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
node1_1  | [info] Done updating.
node1_1  | [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
seed_1   | [info] Compiling 15 Scala sources to /development/target/scala-2.12/classes ...
node2_1  | [info] Compiling 15 Scala sources to /development/target/scala-2.12/classes ...
node1_1  | [info] Compiling 15 Scala sources to /development/target/scala-2.12/classes ...
node1_1  | [info] Done compiling.
seed_1   | [info] Done compiling.
node1_1  | [info] Packaging /development/target/scala-2.12/scalachain_2.12-0.1.jar ...
node1_1  | [info] Done packaging.
node1_1  | [info] Running com.elleflorio.scalachain.Server 0.0.0.0 8080
seed_1   | [info] Packaging /development/target/scala-2.12/scalachain_2.12-0.1.jar ...
seed_1   | [info] Done packaging.
seed_1   | [info] Running com.elleflorio.scalachain.Server 0.0.0.0 8080
```
They differs in particular where it sets the sbt project.
**Your**
```
node2_1  | [warn] No sbt.version set in project/build.properties, base directory: /development
node1_1  | [warn] No sbt.version set in project/build.properties, base directory: /development
seed_1   | [warn] No sbt.version set in project/build.properties, base directory: /development
node2_1  | [info] Set current project to development (in build file:/development/)
node1_1  | [info] Set current project to development (in build file:/development/)
seed_1   | [info] Set current project to development (in build file:/development/)
```
**Mine**
```
node1_1  | [info] Loading project definition from /development/project
seed_1   | [info] Loading project definition from /development/project
node2_1  | [info] Loading project definition from /development/project
seed_1   | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node1_1  | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node2_1  | [info] Updating ProjectRef(uri("file:/development/project/"), "development-build")...
node1_1  | [info] Done updating.
node2_1  | [info] Done updating.
seed_1   | [info] Done updating.
seed_1   | [info] Loading settings for project development from build.sbt ...
seed_1   | [info] Set current project to scalachain (in build file:/development/)
node2_1  | [info] Loading settings for project development from build.sbt ...
node1_1  | [info] Loading settings for project development from build.sbt ...
node2_1  | [info] Set current project to scalachain (in build file:/development/)
node1_1  | [info] Set current project to scalachain (in build file:/development/)
```
Did you try to rebuild the image from scratch after removing the old one?
